urls:
  member-service: http://snowball-class.shop:30001
  lesson-service: http://snowball-class.shop:30002
  payment-service: http://snowball-class.shop:30003
  cart-service: http://snowball-class.shop:30004
  review-service: http://snowball-class.shop:30005
  admin-service: http://snowball-class.shop:30006
  view-service: http://snowball-class.shop:30007

server:
  port: 8087

spring:
  application:
    name: view-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.177.168:3306/mysql8?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: 1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

feign:
  snowball:
    member: ${urls.member-service}
    lesson: ${urls.lesson-service}/lessons
    payment: ${urls.payment-service}
    cart: ${urls.cart-service}
    review: ${urls.review-service}
    admin:
      event: ${urls.admin-service}/events

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
    urls:
      - name: view-service
        url: ${urls.view-service}/v3/api-docs
      - name: lesson-service
        url: ${urls.lesson-service}/v3/api-docs
      - name: admin-service
        url: ${urls.admin-service}/v3/api-docs
  api-docs:
    groups:
      enabled: true

tag:
  version: 1.0.0